/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface NavigationComponent {
      'menus': { id: number, name: string, url: string }[];
    }
  }

  interface HTMLNavigationComponentElement extends StencilComponents.NavigationComponent, HTMLStencilElement {}

  var HTMLNavigationComponentElement: {
    prototype: HTMLNavigationComponentElement;
    new (): HTMLNavigationComponentElement;
  };
  interface HTMLElementTagNameMap {
    'navigation-component': HTMLNavigationComponentElement;
  }
  interface ElementTagNameMap {
    'navigation-component': HTMLNavigationComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'navigation-component': JSXElements.NavigationComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface NavigationComponentAttributes extends HTMLAttributes {
      'menus'?: { id: number, name: string, url: string }[];
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProductCard {
      'contractLength': string;
      'features': string;
      'imageName': string;
      'price': string;
      'productName': string;
    }
  }

  interface HTMLProductCardElement extends StencilComponents.ProductCard, HTMLStencilElement {}

  var HTMLProductCardElement: {
    prototype: HTMLProductCardElement;
    new (): HTMLProductCardElement;
  };
  interface HTMLElementTagNameMap {
    'product-card': HTMLProductCardElement;
  }
  interface ElementTagNameMap {
    'product-card': HTMLProductCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'product-card': JSXElements.ProductCardAttributes;
    }
  }
  namespace JSXElements {
    export interface ProductCardAttributes extends HTMLAttributes {
      'contractLength'?: string;
      'features'?: string;
      'imageName'?: string;
      'price'?: string;
      'productName'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
